In [1]:
!pip install numpy pandas

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 222.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 220.2 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 219.4 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 239.5 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 233.0 kB/s eta 0:00:00
  Using cached pandas-2.2.0-cp310-cp310-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 1.7 MB/s eta 0:00:10
    --------------------------------------- 0.3/15.8 MB 2.7 MB/s eta 0:00:06
   - -------------------------------------- 0.5/15.8 MB 3.4 MB/s eta 0:00:05
   - ----------

In [2]:
import numpy as np

In [4]:
A = [1,2,3,4,5,]
A

[1, 2, 3, 4, 5]

In [7]:
B = np.array([1,2,3,4,5,])
B

array([1, 2, 3, 4, 5])

In [9]:
import sys
# size of array
size_array = sys.getsizeof(1) * len(A)
print("Size array A: ", size_array)

Size array A:  140


In [11]:
#size of numpy array
size_numpy = B.itemsize * B.size
print("Size numpy: ", size_numpy)

Size numpy:  20


In [18]:
# A matrix of 2 x 5
A = np.array([
    [1,2,3,4,5,],
    [6,7,8,9,10]
])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
A.shape

(2, 5)

In [20]:
# Flatten convierte cualquier lector en una sola dimensión
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Por lo tanto la shape del array A cambia a (10,)
A.flatten().shape

(10,)

In [23]:
# Reshape siempre necesita argumentos para funcionar, permite reordenar matrices en las dimensiones dadas
A.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
# Reshape funciona como un comodín, le indica a numpy que no importa cuántas filas tenga, siempre y cuando se cumplan las columnas especificadas
# Viceversa también aplica
A.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
A.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
A.reshape(5,-1,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [37]:
B = np.arange(0,100)
B.shape

(100,)

In [38]:
B.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
zeros = np.zeros([10,2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
ones = np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Python interpreta las listas como un string
A = [1,2,3,]
A * 2

[1, 2, 3, 1, 2, 3]

In [43]:
A = np.array([1,2,3,])
A * 2

array([2, 4, 6])

In [46]:
B = np.array([4,5,6,])
A+B

array([5, 7, 9])

In [47]:
print(A,B)
A*B

[1 2 3] [4 5 6]


array([ 4, 10, 18])

In [48]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.mean(A)

2.0

In [50]:
np.median(A)

2.0

In [51]:
# np.where nos permite obtener los índices de aquellos elementos del array que cumplen con la condición dada
A = np.array([1,2,0,4,5,6,])
C = np.where(A>2)
C

(array([3, 4, 5], dtype=int64),)

# Dot Product

In [52]:
def dot_product(a,b):
    result = 0
    for i in range(len(a)):
        result = result + a[i]*b[i]
    return result

In [62]:
a = np.random.randn(10000000)
b = np.random.randn(10000000)
print(dot_product(a,b))

-3202.3255285396394


In [63]:
import time 

start = time.time()

dot_product(a,b)

total = time.time() - start
print("total time: ", total)

total time:  4.435487985610962


In [76]:
# Numpy es mucho más rápido multiplicando arrays
start = time.time()

print(np.dot(a,b))

total = time.time() - start
print("total time: ", total)

-3202.3255285401083
total time:  0.009476184844970703
